### ISSUE TITLE
Getting an error with Media.play_modal

### ISSUE THREAD

**Issue by bb-cyrus** [rubymotion/BubbleWrap#189]
I was trying to use the media section of bubble-wrap to play sound clips on my app. I have successfully used the play method like the documentation suggests:

```
BW::Media.play(local_file) { |media_player| ... }
```

But I get an error when trying to use the play_modal method according to the documentation code:

```
BW::Media.play_modal(local_file)
```

Output:

```
uncaught exception 'NameError', reason: 'player.rb:90:in `play:': uninitialized constant BubbleWrap::Media::Player::App (NameError)
from player.rb:18:in `play_modal:'
```

This error points to some code in player.rb

```
if display_modal
  @presenting_controller = options[:controller]
  @presenting_controller ||= App.window.rootViewController
  @presenting_controller.presentMoviePlayerViewControllerAnimated(@media_player)
```

I took a peek in the code, but am not sure why `App` has not been initialized here. Anyone have a working example of play_modal? 

Thanks!

**Comment by zxiest** [comment]
FYI, I have to require 'bubble-wrap/core' still for BW::Media to work
