### ISSUE TITLE
BW::SMS.compose does not work

### ISSUE THREAD

**Issue by kapso** [rubymotion/BubbleWrap#327]
Not sure if this is a RubyMotion issue or BW but posting it here. I am getting the following error when composing SMS message. I am running this on iOS simulator, with BW v1.4.0 and RubyMotion v2.17

`undefined method 'messageComposeDelegate=' for nil:NilClass (NoMethodError)`

Its probably this line:
https://github.com/rubymotion/BubbleWrap/blob/72b6f444b35c961f2a9e1784fdbee079461694fa/motion/sms/sms.rb#L31

This is the result from MotionRuby console:

``` ruby
(main)> MFMessageComposeViewController.alloc.init
=> nil
```

my Rakefile:

``` ruby
app.frameworks += %w(Social Twitter MessageUI AddressBookUI)
```

**Comment by GunaSekharM** [comment]
hi,
 i am getting an error called undefined method can_send_sms? i am using BubbleWrap version 1.7.1
