### ISSUE TITLE
uninitialized constant BubbleWrap::Constants (NameError)

### ISSUE THREAD

**Issue by RobertAudi** [rubymotion/BubbleWrap#337]
I just created [my first RubyMotion gem](https://github.com/AzizLight/motion-iconic). I do not know if this issue is related to my gem, or if my gem exposed a bug in BubbleWrap. But when I add both BubbleWrap and my gem to the Gemfile, the simulator crashes with the error: `uninitialized constant BubbleWrap::Constants (NameError)`...

I looked at the code in BubbleWrap, and my gem does not seem to override anything, everything is namespaced...

**Comment by chrise86** [comment]
I've found that `awesome_print_motion` can also trigger this issue. Suggest switching to `motion_print`.

**Comment by markrickert** [comment]
yessss... you should use my motion_print gem :)
