### ISSUE TITLE
Can't get the location

### ISSUE THREAD

**Issue by GCorbel** [rubymotion/BubbleWrap#449]
In app_delegator.rb, I just copied and pasted the example code for location : 

    BW::Location.get(purpose: 'We need to use your GPS because...') do |result|
      p "From Lat #{result[:from].latitude}, Long #{result[:from].longitude}"
      p "To Lat #{result[:to].latitude}, Long #{result[:to].longitude}"
    end

I added bubble-wrap to the Gemfile and I required `bubble-wrap/location`.

It just do nothing. When I do `BW::Location.enabled?` it returns true.

Did I miss something?

**Comment by markrickert** [comment]
Perhaps this? https://github.com/rubymotion/BubbleWrap#ios-8-location-requirements

**Comment by GCorbel** [comment]
Thanks for the very fast anwser (just a minute). It seems to be better but I have the result `{:error=>3}`. It is probably not related to BubbleWrap.

**Comment by markrickert** [comment]
We've been having some issues with location and i'm going to be working on fixing them soon. but for now can you try pointing your project at @cognitiveflux's branch?

```ruby
gem 'bubble-wrap', github: 'cognitiveflux/BubbleWrap', branch: 'Fix_Location_KCLErrorLocationUnknown_restart'
```

And let me know if that fixes the error?

Also, note that the ios simulator is picky about locations... sometimes you have to turn the location OFF, then back on again in the simulator's debug menu or you'll get an error.

**Comment by GCorbel** [comment]
No, I didn't solve the bug.

**Comment by GCorbel** [comment]
It works now. I don't really now what I did.

I tried to do 

    BW::Location.get.startUpdatingLocation
    BW::Location.get.stopUpdatingLocation

And I changed the position in the Simulator settings. It strange because I tried this before without success. Now, it works.

Thanks for your fast help !

**Comment by markrickert** [comment]
Yeah, changing the position sometimes will reset the location's internals.... Apple really needs to fix this.

Glad you got it working!

Was it with the fork i told you to try or with the main bubblewrap repos?

**Comment by GCorbel** [comment]
Yes, it works with the master branch. I rebooted the mac to be sure... And I already try to change the position in the emulator. It's stange...

Thanks again.
