### ISSUE TITLE
Missing constants in BubbleWrap in rubymotion 3.8

### ISSUE THREAD

**Issue by poc7667** [rubymotion/BubbleWrap#455]
I got `#<NameError: uninitialized constant BubbleWrap::HTTP>`,

And I have no idea what's wrong with it

There is no **HTTP** method in **BW** object.

		BW.constants.grep(/htt/mi)
		=> [:MCHTTPRequestor, :NSHTTPURLResponseInternal, :NSHTTPURLResponse, :MCGlobalHTTPProxyPayload, :NSHTTPURLRequestParameters, :NSHTTPCookieStorage, :MCHTTPTransaction, :NSHTTPCookieStorageInternal, :NSHTTPCookie, :CILightTunnel]

	(main)> BW::HTTP
	2015-04-14 13:27:51.673 hello[80662:629086] uninitialized constant BubbleWrap::HTTP (NameError)
	=> #<NameError: uninitialized constant BubbleWrap::HTTP>

	% motion --version
	3.8

	-  bubble-wrap (1.8.0)

**Comment by markrickert** [comment]
HTTP was deprecated in Bubblewrap 1.8.0. If you still want to use it, you can include the bubblewrap-http gem but I highly recommend that you use a more robust solution like afmotion. As far as I know, bubblewrap-http is not maintained or supported.
