### ISSUE TITLE
BW causing compile fatal when using facebook-ios-sdk 4.0+

### ISSUE THREAD

**Issue by rromanchuk** [rubymotion/BubbleWrap#456]
https://github.com/rromanchuk/DebugFacebookSDK

Undefined symbols for architecture i386:
  "_NSString", referenced from:
      _MREP_07D9E30DC95244B8B8FE358E8B09CD44 in string.rb.o
     (maybe you meant: _NSStringFromFBSDKAppGroupPrivacy, _Init_NSString , _NSStringFromFBSDKLikeControlHorizontalAlignment , _NSStringFromFBSDKLikeControlAuxiliaryPosition , _NSStringFromFBSDKShareDialogMode , _NSStringFromFBSDKLikeObjectType , _NSStringFromFBSDKLikeControlStyle )
ld: symbol(s) not found for architecture i386

**Comment by gnestor** [comment]
I noticed that Bubblewrap's font.rb was causing the compile error. I removed `require 'bubble-wrap/all'` and added `require 'bubble-wrap/reactor'` to include Bubblewrap's "Eventable" library and it compiled. In fact, I removed Facebook SDK and tried to compile without it and I got the same error, so I believe that Bubblewrap's font.rb is not compatible with iOS SDK 8.3?

**Comment by markrickert** [comment]
I'm not sure what would be causing a problem in the font file... the bubblewrap sample apps in the repo compile just fine.

With the demo app linked above, removing the facebook code and building shows that bubblewrap is compiling just fine. i don't think this is a bubblewrap problem. 

@rromanchuk what is the status of this?

**Comment by paddingtonsbear** [comment]
@rromanchuk Do you have a work around for this issue, I am currently facing the problem in my rubymotion project. 
Link to your post on the rubymotion community
http://community.rubymotion.com/t/who-has-successfully-integrated-facebook-ios-sdk-v4-0/271/27

**Comment by rromanchuk** [comment]
Looks like i just patched all my gems lol   \_(ツ)_/¯

https://github.com/rromanchuk/twittermotion/commit/aa7eb3b6f4797c1bb2b05cc873a3df3a1ee0d488

https://github.com/rromanchuk/BubbleWrap/commit/23ebb4e899533b9d36299457998dd0d0081d4c03


 http://hipbyte.myjetbrains.com/youtrack/issue/RM-851

**Comment by paddingtonsbear** [comment]
basically patch all gems and not touch the FB SDK?

**Comment by rromanchuk** [comment]
Yup, i just pulled @markrickert changes into my fork, and then made similar changes to other gems

**Comment by paddingtonsbear** [comment]
:+1:

**Comment by markrickert** [comment]
I'll ping HipByte about this bug report and see what can be done. I don't think we should have to change our correctly coded gems because of some weird thing with the clang compiler that causes the Facebook pod to not play nicely.

**Comment by markrickert** [comment]
This should be fixed in RM > 3.12
