### ISSUE TITLE
App Version 

### ISSUE THREAD

**Issue by tombroomfield** [rubymotion/BubbleWrap#459]
Hi All, love using BubbleWrap.

I have read through the API and could just be missing something, I know it is possible to access the current App's version and build number through ObjC, and it feels like something that should be included in BubbleWrap under the App category. I would love to submit a pull request for the feature if possible.

What do you think?

Tom

**Comment by markrickert** [comment]
Hey Tom,

You can access the app's version (`CFBundleVersion`)  with `App.version`.

I'd welcome a PR that added documentation to the readme as well as perhaps `App.short_version` to pull out the `CFBundleShortVersionString` (with tests, of course!)

**Comment by tombroomfield** [comment]
Brilliant, I'll put it together tonight and shoot it over.
