### ISSUE TITLE
Possible to only require JSON helpers?

### ISSUE THREAD

**Issue by andrewhavens** [rubymotion/BubbleWrap#462]
I don't see this mentioned in the documentation. I see that you can `require bubble-wrap/whatever` but I don't see anything about JSON. I tried `require bubble-wrap/json` and `bubble-wrap/core/json` but neither of those worked. Is there an undocumented way of doing this?

**Comment by markrickert** [comment]
Not that I know of. If you're JUST looking for the JSON stuff from BubbleWrap, i'd suggest just pulling the one file out and including it in your application: https://github.com/rubymotion/BubbleWrap/blob/master/motion/core/json.rb

Hopefully that will work for you if you don't need the entire power of BubbleWrap.
