### ISSUE TITLE
[IMPORTANT] ios9 build crashing on bubblewrap  

### ISSUE THREAD

**Issue by rromanchuk** [rubymotion/BubbleWrap#463]
/Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -fexceptions -c -arch arm64 -miphoneos-version-min=7.1 "./build/iPhoneOS-7.1-Release/objs/Users/ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/BubbleWrap-23ebb4e89953/lib/bubble-wrap/version.rb.arm64.bc" -o "./build/iPhoneOS-7.1-Release/objs/Users/ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/BubbleWrap-23ebb4e89953/lib/bubble-wrap/version.rb.arm64.o"
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 7.0.0 (clang-700.0.53)
Target: aarch64-apple-darwin15.0.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
/Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -fexceptions -c -arch arm64 -miphoneos-version-min=7.1 "./build/iPhoneOS-7.1-Release/objs/Users/ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/BubbleWrap-23ebb4e89953/motion/util/deprecated.rb.arm64.bc" -o "./build/iPhoneOS-7.1-Release/objs/Users/ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/BubbleWrap-23ebb4e89953/motion/util/deprecated.rb.arm64.o"
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 7.0.0 (clang-700.0.53)
Target: aarch64-apple-darwin15.0.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
/Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -fexceptions -c -arch arm64 -miphoneos-version-min=7.1 "./build/iPhoneOS-7.1-Release/objs/Users/ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/BubbleWrap-23ebb4e89953/motion/shortcut.rb.arm64.bc" -o "./build/iPhoneOS-7.1-Release/objs/Users/ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/BubbleWrap-23ebb4e89953/motion/shortcut.rb.arm64.o"
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 7.0.0 (clang-700.0.53)
Target: aarch64-apple-darwin15.0.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
/Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -fexceptions -c -arch arm64 -miphoneos-version-min=7.1 "./build/iPhoneOS-7.1-Release/objs/Users/ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/twittermotion-aa7eb3b6f479/lib/twittermotion/version.rb.arm64.bc" -o "./build/iPhoneOS-7.1-Release/objs/Users/ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/twittermotion-aa7eb3b6f479/lib/twittermotion/version.rb.arm64.o"
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 7.0.0 (clang-700.0.53)
Target: aarch64-apple-darwin15.0.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
rake aborted!
Command failed with status (254): [/Applications/Xcode-Beta.app/Contents/Deve...]
/Library/RubyMotion/lib/motion/project/builder.rb:153:in `block (2 levels) in build'
/Library/RubyMotion/lib/motion/project/builder.rb:131:in `each'
/Library/RubyMotion/lib/motion/project/builder.rb:131:in `block in build'
/Library/RubyMotion/lib/motion/project/paralel_builder.rb:47:in `call'
/Library/RubyMotion/lib/motion/project/paralel_builder.rb:47:in `block (2 levels) in initialize'
Tasks: TOP => beta => archive => build:device
(See full trace by running task with --trace)

**Comment by rromanchuk** [comment]
Also, arm64  is not supported with Xcode 7 at this point, so you will have to remove it  from app.archs['iPhoneOS'] when doing device builds.

**Comment by markrickert** [comment]
Yikes! Scary message! :skull: 

I'll probably be waiting till iOS 9 is more mature before worrying about these kinds of things.
