### ISSUE TITLE
BubbleWrap::Location overriding ::Location

### ISSUE THREAD

**Issue by awernick** [rubymotion/BubbleWrap#464]
Having a Location class defined in a RubyMotion project, I noticed that BubbleWrap::Location overrides the local class. After digging around the source, I found the culprit:
https://github.com/rubymotion/BubbleWrap/blob/aabbcd30c5bf841bffb623e15322d452b7e313c7/motion/location/location.rb#L237

Even tough BubbleWrap checks if the constant is defined, at runtime (or compile time?), the local constant has not been defined yet, so BubbleWrap overrides the constant.

**Comment by markrickert** [comment]
Yeah, I'm not sure why they did that... seems like defining a `Location` class without a namespace would cause collisions for a lot of people. It would be difficult for me to depreciate it anytime soon, so unfortunately you'll have to use a different class name for yours. Sorry :cry:

**Comment by awernick** [comment]
:sweat: alright. I was able to keep my class name by namespacing my model, but its kinda tedious having to write the whole namespace + class name sometimes. I guess I'll just have to modify my local of copy of the gem to solve my needs. Thanks anyway!

**Comment by markrickert** [comment]
Sorry, bud.
